### ISSUE TITLE
create PMA zone partition in master database

### ISSUE THREAD

**Issue by dong-bellevue** [bellevuewa/BKRCast#84]

**Comment by nbleich** [comment]
Created extra attribute @pmatype with unique identifiers for each area. The extra attribute has been added to Scenario 8046 for the Spring Blvd analysis. I added the classification to attribute description:   11=Downtown, 12=Wilburton, 13=BelRed, 21= Factoria, 22=Eastgate, 23= Crossroads, 30=Residential, 0=Outside Bellevue. Since they share the same PMA number, I added a second digit to create the unique ID so we could select some but not all of a specific PMA type. I exported the network from EMME and used a spatial join in ArcGIS to attach the attribute. Then I refined the join to capture roadways that follow the borders between PMAs. 

![image](https://user-images.githubusercontent.com/116830892/235254706-0b15314e-df4d-4f88-9848-344326a7d492.png)

**Comment by dong-bellevue** [comment]
Just got chance to look into this. @pmatype you created is link attributes for PMA, but not a zone partition. This one will have its own use, so we can keep it.

Zone partition is used to group a number of centroids. Most of the use is in matrix calculation. You can read the user manual for more details. We have a few zone partitions defined in the master network. You can take a look ga or gb and then you will know what it looks like.

Thanks. Let me know if you have any questions.

Hu

**Comment by nbleich** [comment]
I have created a zone partition for the PMA areas using the same code as the link PMAType attribute in master network scenario 8047. 11=Downtown, 12=Wilburton, 13=BelRed, 21= Factoria, 22=Eastgate, 23= Crossroads, 30=Residential, 0=Outside Bellevue

**Comment by nbleich** [comment]
Here is an example from the Zone Partition export of Scenario 8047: 

![image](https://github.com/bellevuewa/BKRCast/assets/116830892/32e5476d-bc67-4156-bc8e-d680f3c2ca15)
