### ISSUE TITLE
Update transit assignment specs.

### ISSUE THREAD

**Issue by dong-bellevue** [bellevuewa/BKRCast#88]
So far, we can run auto assignment in the modeller with auto assignment specs. We need to do the same thing for transit assignment by creating a transit assignment specs.

The current transit assignment specs is outdated (was done before LRT was modeled as a transit submode).

**Comment by nbleich** [comment]
@dong-bellevue, 

For this update, are we looking to create a combined EMME Flow spec that will run all of the transit assignment steps in order, similar to how the skimandpaths.py executes the assignment? Since we have separate demand matrices for each submode from Daysim, I don't think we can create a single extended transit assignment. 

Looking into the EMME Logbook, it should be fairly straightforward to recreate the steps as an EMME Flow spec that will run the transit assignments in order in modeler, but I have a couple questions. I have included a screenshot below of the EMME Logbook for the transit assignment that shows all of the steps executed by skimandpaths.py. 

1. For this spec should I include the initialization steps for the transit assignment: Create Node Extra Attribute and Network Calculations? If we are running the transit assignment on a model that was already run, then these should already be created and won't need to be included in this spec. 
2. Should I include the Extended Transit Matrix Analysis for each submode and the matrix calculations at the end of the assignment? These calculations appear to be part of the overall assignment and likely should be included in the EMME Flow spec. 

Nick 


![image](https://github.com/bellevuewa/BKRCast/assets/116830892/f1b0ba8f-786a-4a35-94ff-77d0d97dd823)

**Comment by dong-bellevue** [comment]
Thanks for bringing this to me. You are right. Transit assignment requires multiple assignments on submodes. We need to create a separate transit assignment tool in order to run it separately. I will reassign it back to me.

Hu
